### ISSUE TITLE
make the archive searchable

### ISSUE THREAD

**Issue by crackmonkeyz** [preservetube/preservetube#1]
hello i am a user of this project and love it but theres one flaw that needs to be addressed theres no easy way to search through the entire archive of videos if you added this with the ablity to download or torrent them aswell it would improve the project

**Comment by unknownsrc** [comment]
> no easy way to search through the entire archive of videos
> the ablity to download

Added in https://github.com/preservetube/preservetube/commit/d9d62bb435db041ed05ce4b2da697bc60a30fc21

> torrent them aswell
This isn't really possible with my current architecture because the files are uploaded directly to Minio. I have no idea how I could even add this.
