### ISSUE TITLE
Footer getting overlaid on top of other elements

### ISSUE THREAD

**Issue by 4rnv** [preservetube/preservetube#12]
# Description

![screenshot_preservetube com_X](https://github.com/preservetube/preservetube/assets/146211212/e66269b9-7f3f-4ffd-afd5-f6972486b917)

The footer on the homepage is laid on top of the other elements. I tested this on both Chromium and Firefox browsers, seems to be a CSS issue.

**Comment by unknownsrc** [comment]
Fixed in https://github.com/preservetube/preservetube/pull/17
