### ISSUE TITLE
[PRSV-13] Crazy slow downloads

### ISSUE THREAD

**Issue by unknownsrc** [preservetube/preservetube#15]
I have absolutely no idea why...

<sub>[PRSV-13](https://linear.app/tndllc/issue/PRSV-13/crazy-slow-downloads)</sub>

**Comment by unknownsrc** [comment]
My autism went on turbo mode and got this fixed.

**Comment by dieperdev** [comment]
https://www.youtube.com/watch?v=ktxbXlF6UQE
![image](https://github.com/preservetube/preservetube/assets/140034404/e6717996-a6dd-44e9-8455-e80dcbfe29a1)

**Comment by dieperdev** [comment]
@unknownsrc Has the "legal cannon of doom" reached out to you yet? It appears that some other issues have been opened (and you closed them) regarding the situation. Respectively: #8 , #9 , and #10 . Innocent until proven guilty.
