### ISSUE TITLE
Searching breaks browser history with a weird error message

### ISSUE THREAD

**Issue by TangentFoxy** [preservetube/preservetube#21]
I was searching for something and then went back to try a different search, and PreserveTube served a very strange and somewhat offensive error message.

![image](https://github.com/user-attachments/assets/98874cfd-4b46-4e4a-9656-020b9e287c0e)

I don't think I need to elaborate on why this is bad.

**Comment by unknownsrc** [comment]
While I do not appreciate the way you worded your issue, it's fair to acknowledge that not everyone understands the inside joke; therefore, a clearer error message would be more appropriate.

**Comment by TangentFoxy** [comment]
> While I do not appreciate the way you worded your issue

Please tell me what specifically I should change so that I may communicate better in the future.
